server:
  port: 8088

spring:
  application:
    name: vis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.234.248:3306/knowledgeVis?characterEncoding=utf-8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:

      #初始化时建立物理连接的个数
      initial-size: 3
      #  最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 10
      #获取连接时最大等待时间
      max-wait: 60000
      #配置监控页面访问登录名及密码
      stat-view-servlet:
        login-username: admin
        login-password: 123456
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1

mybatis:
  #domain对象的包
  type-aliases-package: xmu.vis.domain
  #mapper.xml所在的位置
  mapper-locations: classpath:xmu.vis.mapper/*.xml
  configuration:
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true
#
#logging:
#  #设置日志打印级别
#  level:
#    #Spring框架中的日志级别
#    org.springframework.web: info
#    root: error
#    #自己项目包名下的日志级别
#    xmu.oomall.controller: debug
#    xmu.oomall.service: debug
#    xmu.oomall.dao: debug
#    xmu.oomall.mapper: error
#    xmu.oomall.domain: debug
#    xmu.oomall.util: debug
#  #使用logback日志，取代默认的common日志
#  file:
#    path: ~/minichat/log
##  config: classpath:logback-spring.xml